-- =============================================================
-- VPPT — Vendor & Procurement Performance Tracker
-- File: 04_procurement.sql
-- Purpose: purchase_requisitions, purchase_requisition_items,
--          purchase_orders, purchase_order_items,
--          procurement_stage_logs, deliveries,
--          quality_inspections, returns
-- Run after: 01_users_roles.sql, 02_vendors.sql, 03_hardware_inventory.sql
-- =============================================================

USE vppt;

-- -------------------------------------------------------------
-- Table: purchase_requisitions
-- PR header. All business-stage timestamps are stored here so
-- the bottleneck service can calculate PR-side durations
-- (PR Created → PR Reviewed → Dept Approved → Proc Approved).
-- Once procurement_approved_at is set the PR can be converted
-- to a Purchase Order.
-- pr_number format: PR-YYYY-NNNN (generated by the application).
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_requisitions (
    pr_id                   INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    pr_number               VARCHAR(30)     NOT NULL
                            COMMENT 'Application-generated, e.g. PR-2025-0001',
    requested_by_id         INT UNSIGNED    NOT NULL,
    department_id           INT UNSIGNED    NOT NULL,
    priority                ENUM(
                                'low',
                                'normal',
                                'high',
                                'urgent'
                            )               NOT NULL DEFAULT 'normal',
    status                  ENUM(
                                'draft',
                                'under_review',
                                'dept_approved',
                                'procurement_approved',
                                'converted_to_po',
                                'rejected',
                                'cancelled'
                            )               NOT NULL DEFAULT 'draft',
    total_estimated_cost    DECIMAL(15,2)       NULL DEFAULT NULL
                            COMMENT 'Sum of (qty_requested × est_unit_cost) across line items',

    -- Workflow timestamps (all business datetimes, not audit timestamps)
    pr_created_at           DATETIME        NOT NULL
                            COMMENT 'When the PR was formally submitted',
    pr_reviewed_at          DATETIME            NULL DEFAULT NULL,
    department_approved_at  DATETIME            NULL DEFAULT NULL,
    procurement_approved_at DATETIME            NULL DEFAULT NULL,

    -- Who performed each workflow step
    reviewed_by_id          INT UNSIGNED        NULL DEFAULT NULL,
    dept_approved_by_id     INT UNSIGNED        NULL DEFAULT NULL,
    proc_approved_by_id     INT UNSIGNED        NULL DEFAULT NULL,

    rejection_reason        TEXT                NULL DEFAULT NULL,
    notes                   TEXT                NULL DEFAULT NULL,

    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                            ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_pr                PRIMARY KEY  (pr_id),
    CONSTRAINT uq_pr_number         UNIQUE       (pr_number),
    CONSTRAINT fk_pr_requester      FOREIGN KEY  (requested_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_pr_department     FOREIGN KEY  (department_id)
        REFERENCES departments (department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_pr_reviewer       FOREIGN KEY  (reviewed_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_pr_dept_approver  FOREIGN KEY  (dept_approved_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_pr_proc_approver  FOREIGN KEY  (proc_approved_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    INDEX idx_pr_requester          (requested_by_id),
    INDEX idx_pr_department         (department_id),
    INDEX idx_pr_status             (status),
    INDEX idx_pr_priority           (priority),
    INDEX idx_pr_created_at         (pr_created_at)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Purchase Requisition headers. Stage timestamps support bottleneck analysis.';


-- -------------------------------------------------------------
-- Table: purchase_requisition_items
-- Line items for each PR. Links the requested hardware_item,
-- quantity, and cost estimate.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_requisition_items (
    pri_id                  INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    pr_id                   INT UNSIGNED    NOT NULL,
    item_id                 INT UNSIGNED    NOT NULL,
    quantity_requested      INT UNSIGNED    NOT NULL,
    estimated_unit_cost     DECIMAL(15,2)       NULL DEFAULT NULL
                            COMMENT 'Cost estimate at time of request; may differ from actual PO price',
    justification           TEXT                NULL DEFAULT NULL,

    CONSTRAINT pk_pri               PRIMARY KEY  (pri_id),
    CONSTRAINT fk_pri_pr            FOREIGN KEY  (pr_id)
        REFERENCES purchase_requisitions (pr_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_pri_item          FOREIGN KEY  (item_id)
        REFERENCES hardware_items (item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_pri_pr                (pr_id),
    INDEX idx_pri_item              (item_id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Line items for a Purchase Requisition.';


-- -------------------------------------------------------------
-- Table: purchase_orders
-- PO header. Contains all workflow timestamps from PO creation
-- through to completion. These are the primary inputs for the
-- procurement bottleneck analysis.
-- pr_id is nullable to support direct POs (raised without a PR).
-- expected_delivery_date is set at creation from vendor SLA lead time.
-- po_number format: PO-YYYY-NNNN (generated by the application).
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_orders (
    po_id                   INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    po_number               VARCHAR(30)     NOT NULL
                            COMMENT 'Application-generated, e.g. PO-2025-0001',
    pr_id                   INT UNSIGNED        NULL DEFAULT NULL
                            COMMENT 'Source PR; NULL for direct POs',
    vendor_id               INT UNSIGNED    NOT NULL,
    department_id           INT UNSIGNED    NOT NULL,
    created_by_id           INT UNSIGNED    NOT NULL,
    status                  ENUM(
                                'pending',
                                'acknowledged',
                                'processing',
                                'shipped',
                                'delivered',
                                'inspected',
                                'completed',
                                'cancelled'
                            )               NOT NULL DEFAULT 'pending',
    total_amount            DECIMAL(15,2)   NOT NULL DEFAULT 0.00,
    currency                CHAR(3)         NOT NULL DEFAULT 'MYR'
                            COMMENT 'ISO 4217 currency code',

    -- Workflow timestamps (business datetimes, not system audit timestamps)
    po_created_at           DATETIME        NOT NULL,
    vendor_acknowledged_at  DATETIME            NULL DEFAULT NULL,
    order_processing_at     DATETIME            NULL DEFAULT NULL,
    shipped_at              DATETIME            NULL DEFAULT NULL,
    delivered_at            DATETIME            NULL DEFAULT NULL,
    inspection_completed_at DATETIME            NULL DEFAULT NULL,
    completed_at            DATETIME            NULL DEFAULT NULL,

    expected_delivery_date  DATE                NULL DEFAULT NULL
                            COMMENT 'po_created_at + vendor SLA lead_time_days',
    notes                   TEXT                NULL DEFAULT NULL,

    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                            ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_po                PRIMARY KEY  (po_id),
    CONSTRAINT uq_po_number         UNIQUE       (po_number),
    CONSTRAINT fk_po_pr             FOREIGN KEY  (pr_id)
        REFERENCES purchase_requisitions (pr_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_po_vendor         FOREIGN KEY  (vendor_id)
        REFERENCES vendors (vendor_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_po_department     FOREIGN KEY  (department_id)
        REFERENCES departments (department_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_po_creator        FOREIGN KEY  (created_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_po_vendor             (vendor_id),
    INDEX idx_po_department         (department_id),
    INDEX idx_po_status             (status),
    INDEX idx_po_created_at         (po_created_at),
    INDEX idx_po_completed_at       (completed_at),
    INDEX idx_po_pr                 (pr_id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Purchase Order headers. All stage timestamps stored here for cycle-time analysis.';


-- -------------------------------------------------------------
-- Table: purchase_order_items
-- Line items for each PO. Tracks what was ordered, received,
-- and rejected at the item level.
-- quantity_rejected feeds into defect/return analysis.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS purchase_order_items (
    poi_id              INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    po_id               INT UNSIGNED    NOT NULL,
    item_id             INT UNSIGNED    NOT NULL,
    quantity_ordered    INT UNSIGNED    NOT NULL,
    unit_price          DECIMAL(15,2)   NOT NULL
                        COMMENT 'Actual agreed PO price per unit',
    total_price         DECIMAL(15,2)   NOT NULL
                        COMMENT 'Computed: quantity_ordered × unit_price',
    quantity_received   INT UNSIGNED    NOT NULL DEFAULT 0
                        COMMENT 'Updated on delivery recording',
    quantity_rejected   INT UNSIGNED    NOT NULL DEFAULT 0
                        COMMENT 'Updated on quality inspection',

    CONSTRAINT pk_poi               PRIMARY KEY  (poi_id),
    CONSTRAINT fk_poi_po            FOREIGN KEY  (po_id)
        REFERENCES purchase_orders (po_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_poi_item          FOREIGN KEY  (item_id)
        REFERENCES hardware_items (item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_poi_po                (po_id),
    INDEX idx_poi_item              (item_id)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Purchase Order line items. qty_received and qty_rejected updated post-delivery.';


-- -------------------------------------------------------------
-- Table: procurement_stage_logs
-- One row per PO per workflow stage. The bottleneck service
-- reads this table to compute average/max duration per stage.
-- duration_hours is computed and stored when exited_at is set:
--   duration_hours = TIMESTAMPDIFF(SECOND, entered_at, exited_at) / 3600
-- stage_name values (enforced at application level):
--   PO_CREATED, VENDOR_ACKNOWLEDGED, ORDER_PROCESSING,
--   SHIPPED, DELIVERED, INSPECTION_COMPLETED, COMPLETED
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS procurement_stage_logs (
    stage_log_id    INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    po_id           INT UNSIGNED    NOT NULL,
    stage_name      VARCHAR(60)     NOT NULL
                    COMMENT 'Stage identifier, e.g. PO_CREATED, SHIPPED, DELIVERED',
    entered_at      DATETIME        NOT NULL
                    COMMENT 'Timestamp when this stage began',
    exited_at       DATETIME            NULL DEFAULT NULL
                    COMMENT 'Timestamp when this stage ended (NULL = still in progress)',
    duration_hours  DECIMAL(10,2)       NULL DEFAULT NULL
                    COMMENT 'Stored: TIMESTAMPDIFF(SECOND, entered_at, exited_at) / 3600',
    performed_by_id INT UNSIGNED        NULL DEFAULT NULL
                    COMMENT 'User who triggered the stage transition',
    notes           TEXT                NULL DEFAULT NULL,

    CONSTRAINT pk_stage_log         PRIMARY KEY  (stage_log_id),
    CONSTRAINT fk_stage_po          FOREIGN KEY  (po_id)
        REFERENCES purchase_orders (po_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_stage_user        FOREIGN KEY  (performed_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    INDEX idx_stage_po              (po_id),
    INDEX idx_stage_name            (stage_name),
    INDEX idx_stage_entered_at      (entered_at),
    INDEX idx_stage_duration        (duration_hours)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Per-stage duration log for each PO. Primary source for bottleneck analysis.';


-- -------------------------------------------------------------
-- Table: deliveries
-- One row per PO (1:1 enforced by UNIQUE on po_id).
-- is_on_time is set when actual_date is recorded:
--   is_on_time = (actual_date <= expected_date) ? 1 : 0
-- This table feeds the On-Time Delivery Rate KPI and chart.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS deliveries (
    delivery_id     INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    po_id           INT UNSIGNED    NOT NULL,
    expected_date   DATE                NULL DEFAULT NULL
                    COMMENT 'Copied from purchase_orders.expected_delivery_date',
    actual_date     DATE                NULL DEFAULT NULL
                    COMMENT 'Date goods were physically received',
    is_on_time      TINYINT(1)          NULL DEFAULT NULL
                    COMMENT '1=on time, 0=late, NULL=not yet delivered',
    courier         VARCHAR(100)        NULL DEFAULT NULL,
    tracking_number VARCHAR(100)        NULL DEFAULT NULL,
    received_by_id  INT UNSIGNED        NULL DEFAULT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                    ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_deliveries        PRIMARY KEY  (delivery_id),
    CONSTRAINT uq_delivery_po       UNIQUE       (po_id)
                                    COMMENT 'One delivery per PO',
    CONSTRAINT fk_delivery_po       FOREIGN KEY  (po_id)
        REFERENCES purchase_orders (po_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_delivery_receiver FOREIGN KEY  (received_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE SET NULL,

    INDEX idx_del_is_on_time        (is_on_time),
    INDEX idx_del_actual_date       (actual_date)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Delivery record per PO. is_on_time feeds vendor on-time delivery scoring.';


-- -------------------------------------------------------------
-- Table: quality_inspections
-- One row per PO (1:1 enforced by UNIQUE on po_id).
-- defect_rate_pct is stored (not recalculated on each read):
--   defect_rate_pct = (units_rejected / total_units_checked) × 100
-- This feeds the vendor quality score and defect heat map.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS quality_inspections (
    inspection_id       INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    po_id               INT UNSIGNED    NOT NULL,
    inspected_by_id     INT UNSIGNED    NOT NULL,
    inspection_date     DATETIME        NOT NULL,
    total_units_checked INT UNSIGNED    NOT NULL DEFAULT 0,
    units_passed        INT UNSIGNED    NOT NULL DEFAULT 0,
    units_rejected      INT UNSIGNED    NOT NULL DEFAULT 0,
    defect_rate_pct     DECIMAL(5,2)    NOT NULL DEFAULT 0.00
                        COMMENT 'Stored: (units_rejected / total_units_checked) × 100',
    outcome             ENUM(
                            'accepted',
                            'partially_accepted',
                            'rejected'
                        )               NOT NULL,
    notes               TEXT                NULL DEFAULT NULL,
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
                                        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_inspections       PRIMARY KEY  (inspection_id),
    CONSTRAINT uq_inspection_po     UNIQUE       (po_id)
                                    COMMENT 'One inspection per PO',
    CONSTRAINT fk_insp_po           FOREIGN KEY  (po_id)
        REFERENCES purchase_orders (po_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_insp_user         FOREIGN KEY  (inspected_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_insp_outcome          (outcome),
    INDEX idx_insp_date             (inspection_date),
    INDEX idx_insp_defect_rate      (defect_rate_pct)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Quality inspection result per PO. defect_rate_pct stored for analytics queries.';


-- -------------------------------------------------------------
-- Table: returns
-- One inspection can produce multiple return records (one per item
-- type returned). po_id is a deliberate denormalization: it avoids
-- a join through quality_inspections in return/defect analysis.
-- quantity_returned feeds the vendor return-rate sub-score.
-- credit_received tracks whether a replacement/credit was issued.
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS returns (
    return_id           INT UNSIGNED    NOT NULL AUTO_INCREMENT,
    inspection_id       INT UNSIGNED    NOT NULL,
    po_id               INT UNSIGNED    NOT NULL
                        COMMENT 'Denormalized from inspection→PO for simpler queries',
    item_id             INT UNSIGNED    NOT NULL,
    quantity_returned   INT UNSIGNED    NOT NULL,
    reason              TEXT            NOT NULL,
    return_date         DATETIME        NOT NULL,
    processed_by_id     INT UNSIGNED    NOT NULL,
    credit_received     TINYINT(1)      NOT NULL DEFAULT 0
                        COMMENT '1 = vendor issued credit or replacement',
    created_at          TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_returns           PRIMARY KEY  (return_id),
    CONSTRAINT fk_return_inspection FOREIGN KEY  (inspection_id)
        REFERENCES quality_inspections (inspection_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_return_po         FOREIGN KEY  (po_id)
        REFERENCES purchase_orders (po_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_return_item       FOREIGN KEY  (item_id)
        REFERENCES hardware_items (item_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_return_user       FOREIGN KEY  (processed_by_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE ON DELETE RESTRICT,

    INDEX idx_return_inspection     (inspection_id),
    INDEX idx_return_po             (po_id),
    INDEX idx_return_item           (item_id),
    INDEX idx_return_date           (return_date)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Return records per inspection. po_id is denormalized for query convenience.';
